---
- name: Create traefik config directory
  ansible.builtin.file:
    path: "{{ traefik_http_service_config_dir }}"
    state: directory
    owner: "{{ traefik_http_service_owner }}"
    group: "{{ traefik_http_service_group }}"
    mode: "0775"
  become: yes

- name: Create traefik config file for {{ traefik_http_service_name }}
  ansible.builtin.template:
    src: http-service.yaml.j2
    dest: "{{ (traefik_http_service_config_dir, traefik_http_service_name) | path_join }}.yaml"
    owner: "{{ traefik_http_service_owner }}"
    group: "{{ traefik_http_service_group }}"
    mode: "0640"
  become: yes

