namespace: ahaydon
name: traefik
version: 0.1.0
readme: README.md
authors:
  - Adam Haydon (https://github.com/ahaydon)
description: Collection of roles and playbooks for deploying Traefik
license_file: LICENSE
tags:
  - traefik
  - podman
  - application
  - linux
dependencies:
  "git+https://github.com/ahaydon/ansible-podman-collection.git": "master"
repository: https://github.com/ahaydon/ansible-traefik-collection
documentation: https://github.com/ahaydon/ansible-traefik-collection
homepage: https://github.com/ahaydon/ansible-traefik-collection
issues: https://github.com/ahaydon/ansible-traefik-collection/issues
build_ignore: []
