---
argument_specs:
  main:
    short_description: Main entrypoint for the traefik_podman role
    description:
      - This is the main entrypoint for the C(traefik_podman) role.
    author: Adam Haydon
    options:
      traefik_podman_home:
        type: path
        required: true
        description:
          - The path to the config and data.

      traefik_podman_email:
        type: str
        required: true
        description:
          - Email address for LetsEncrypt.

      traefik_podman_name:
        type: str
        default: traefik
        description:
          - Name of the container and service.

      traefik_podman_version:
        type: str
        default: latest
        description:
          - The tag to use for the Traefik container image.

      traefik_podman_user:
        type: str
        default: traefik
        description:
          - The name of the user to run the Podman container.

      traefik_podman_group:
        type: str
        default: "{{ traefik_podman_user }}"
        description:
          - The name of the primary group for the traefik user.
